runtime: nodejs20

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /css/.*
  static_dir: public/css
  secure: always

- url: /.*
  script: auto
  secure: always